subscan-explorer/subscan-multisig-react

public/locales/en/translation.json, public/locales/zh/translation.json, src/App.tsx, src/components/Entries.tsx, src/components/Members.tsx, src/components/SubscanLink.tsx, src/components/WalletForm.tsx, src/components/WalletState.tsx, src/components/Wallets.tsx, src/index.scss, src/service/api-provider.tsx
except for Args components and polkadot components
=> style: add responsive layout

src/components/Anime/Anime.tsx, src/components/WalletForm.tsx, src/service/api-provider.tsx
=> fix(#11): network status error

src/packages/react-api/src/Api.tsx, src/service/api-provider.tsx, src/utils/api/index.ts
=> fix(#15): show loading page as soon as rpc disconnected

src/components/ExtrinsicRecords.tsx, src/components/WalletState.tsx
=> fix(#24): confirmed statistic num

src/service/api-provider.tsx
=> fix(#27): delete metamask detect

src/App.tsx
=> fix(#26): align header elements

src/model/index.ts, src/model/storage.ts, src/service/api-provider.tsx, src/utils/api/index.ts, src/utils/helper/storage.ts
The second point mentioned in #25
=> fix(#25): cache network info in localStorage

src/components/SubscanLink.tsx, src/components/Wallets.tsx
=> fix(#38): subscan hyperlink

src/App.tsx
=> fix(#44): github repo link

src/App.tsx, src/components/ExtrinsicLaunch.tsx, src/components/ExtrinsicRecords.tsx, src/components/Members.tsx, src/components/WalletState.tsx, src/components/Wallets.tsx, src/hooks/index.ts, src/hooks/multisig.ts, src/hooks/multisigContext.tsx, src/packages/react-api/src/Api.tsx, src/pages/Extrinsic.tsx, src/service/index.ts, src/service/multisig-provider.tsx
=> add tx reactive

public/locales/en/translation.json, public/locales/zh/translation.json, src/components/Entries.tsx, src/components/ExtrinsicRecords.tsx, src/components/TxApprove.tsx, src/components/TxCancel.tsx, src/components/WalletState.tsx, src/hooks/multiApprove.ts, src/hooks/multisig.ts, src/model/index.ts, src/model/tx.ts, src/service/multisig-provider.tsx, src/utils/helper/common.ts
=> approver selectable

src/components/Args.tsx, src/components/Entries.tsx, src/components/TxCancel.tsx, src/config/network.ts, src/config/types.ts, src/utils/helper/balance.ts, src/utils/helper/types.ts
=> args table algorithm refactor

src/App.tsx, src/components/ThemeSwitch.tsx, src/components/WalletForm.tsx, src/components/WalletState.tsx, tailwind.config.js
=> optimize some UX on mobile

package-lock.json, package.json, src/components/ExtrinsicLaunch.tsx
=> remove external account

src/App.tsx, src/components/Footer.tsx, src/components/Wallets.tsx
=> fix(#66): footer static on mobile

src/components/ThemeSwitch.tsx, src/theme/antd/vars.less
fix #76 
加了下全局配置，细节部分需要检查polkadot 组件使用的 css 变量，应该有的是冲突的
=> fix(#76): dark mode global config

src/components/Entries.tsx, src/components/ExtrinsicRecords.tsx, src/components/TxApprove.tsx, src/components/WalletState.tsx, src/config/network.ts, src/providers/gql-provider.tsx, src/providers/multisig-provider.tsx, src/utils/helper/common.ts
add loop query confirm the count
fix height maybe NaN in subscan link
the first column of the confirmed extrinsic table is block hash, because of the current data structure in subql, it is difficult to query the tx hash directly from the subql endpoint, many stuff needs to be done for that
=> fix(#75): history record

src/packages/react-components/src/Expander.tsx
fix issue: 
https://github.com/itering/subscan-multisig-react/issues/93
=> fix: kusama network approve error

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prd.yml, .github/workflows/deploy-stg.yml, package-lock.json
https://github.com/darwinia-network/crab-docs/pull/111
=> Vercel action

.github/workflows/deploy-dev.yml, .github/workflows/deploy-stg.yml
Add pined domain for dev and stg deployment
multisig-dev.vercel.app
multisig-staging.vercel.app
=> Alias domain for dev and stg deployment

public/locales/en/translation.json, public/locales/zh/translation.json, src/components/WalletForm.tsx, src/components/Wallets.tsx, src/components/icons/export.tsx, src/components/icons/import.tsx, src/index.scss, src/model/account.ts, src/utils/helper/multisig.ts
https://github.com/itering/subscan-multisig-react/issues/138
=> feat: support import/export multiple wallet accounts

src/components/ExtrinsicLaunch.tsx
https://github.com/itering/subscan-multisig-react/issues/184
=> fix: call hash preview mismatch

public/locales/en/translation.json, public/locales/zh/translation.json, src/components/Entries.tsx, src/components/ExtrinsicRecords.tsx, src/config/chains/crab.json, src/config/chains/darwinia.json, src/config/chains/kusama.json, src/config/chains/pangolin.json, src/config/chains/polkadot.json, src/config/query.ts, src/utils/helper/index.ts, src/utils/helper/time.ts
https://github.com/itering/subscan-multisig-react/issues/181
=> feat: add approve type and timestamp in approve record

public/image/parallel.svg, src/config/chains/heiko.json, src/config/chains/parallel.json
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>
=> feat: add parallel & parallel-heiko support

src/config/chains/heiko.json
Signed-off-by: Cheng JIANG <alex_cj96@foxmail.com>
=> fix: parallel-heiko displayName

src/components/ExtrinsicLaunch.tsx, src/components/modals/Transfer.tsx, src/hooks/multiApprove.ts, src/packages/react-signer/src/TxSigned.tsx, src/utils/helper/weight.ts
=> fix: lock submit button when input params

public/locales/en/translation.json, public/locales/zh/translation.json, src/components/Entries.tsx, src/components/TxApprove.tsx, src/model/tx.ts
=> feat: add execute button when the signatures exceeds multisig threshold

package-lock.json, package.json, src/components/Entries.tsx, src/components/ExtrinsicRecords.tsx, src/components/TxApprove.tsx, src/config/chains/darwinia.json, src/config/chains/kusama.json, src/hooks/AxiosRequest.ts, src/hooks/combineQuery.ts, src/hooks/index.ts, src/hooks/multisig.ts, src/hooks/subquery.ts, src/hooks/subscan.ts, src/model/network.ts, src/pages/Extrinsic.tsx, src/providers/multisig-provider.tsx, src/utils/helper/time.ts
fixed https://github.com/subscan-explorer/subscan-multisig-react/issues/220
=> support subscan api

src/providers/api-provider.tsx
dbc chain `ss58Prefix` type is `u8`
=> fix: force conversion ss58format to string
